config/routes.rb
Rails.application.routes.draw do
  resources :balance_divisas
  resources :balance_criptomonedas
  resources :valor_historicos
  resources :criptomonedas
  resources :divisas
  resources :usuarios

  root to:"criptomonedas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format:'json'} do
  	namespace :v1 do
  		resources :balance_divisas
      resources :balance_criptomonedas
      resources :valor_historicos
      resources :criptomonedas
      resources :divisas
      resources :usuarios
  	end
  end
end

app/models/valor_historico.rb
class ValorHistorico < ApplicationRecord
end

app/controllers/api/v1/valor_historicos_controller.rb
module Api
module V1

class ValorHistoricosController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_valor_historico, only: [:show, :update, :destroy]

  # GET /valor_historicos
  def index
    @valor_historicos = ValorHistorico.all.order('fecha DESC')

    render json: @valor_historicos
  end

  # GET /valor_historicos/1
  def show
    render json: @valor_historico
  end

  # POST /valor_historicos
  def create
    @valor_historico = ValorHistorico.new(valor_historico_params)

    if @valor_historico.save
      render json: @valor_historico, status: :created, location: @valor_historico
    else
      render json: @valor_historico.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /valor_historicos/1
  def update
    if @valor_historico.update(valor_historico_params)
      render json: @valor_historico
    else
      render json: @valor_historico.errors, status: :unprocessable_entity
    end
  end

  # DELETE /valor_historicos/1
  def destroy
    @valor_historico.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valor_historico
      @valor_historico = ValorHistorico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def valor_historico_params
      params.require(:valor_historico).permit(:fecha, :valor, :criptomoneda_id)
    end
end
end
end

app/controllers/valor_historicos_controller.rb
class ValorHistoricosController < ApplicationController
  before_action :set_valor_historico, only: %i[ show edit update destroy ]

  # GET /valor_historicos or /valor_historicos.json
  def index
    @valor_historicos = ValorHistorico.all.order('fecha DESC')
  end

  # GET /valor_historicos/1 or /valor_historicos/1.json
  def show
  end

  # GET /valor_historicos/new
  def new
    @valor_historico = ValorHistorico.new
  end

  # GET /valor_historicos/1/edit
  def edit
  end

  # POST /valor_historicos or /valor_historicos.json
  def create
    @valor_historico = ValorHistorico.new(valor_historico_params)

    respond_to do |format|
      if @valor_historico.save
        format.html { redirect_to @valor_historico, notice: "Valor historico was successfully created." }
        format.json { render :show, status: :created, location: @valor_historico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @valor_historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valor_historicos/1 or /valor_historicos/1.json
  def update
    respond_to do |format|
      if @valor_historico.update(valor_historico_params)
        format.html { redirect_to @valor_historico, notice: "Valor historico was successfully updated." }
        format.json { render :show, status: :ok, location: @valor_historico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @valor_historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valor_historicos/1 or /valor_historicos/1.json
  def destroy
    @valor_historico.destroy
    respond_to do |format|
      format.html { redirect_to valor_historicos_url, notice: "Valor historico was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valor_historico
      @valor_historico = ValorHistorico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def valor_historico_params
      params.require(:valor_historico).permit(:fecha, :valor)
    end
end

app/helpers/valor_historicos_helper.rb
module ValorHistoricosHelper
end

app/views/valor_historicos/_form.html.erb
<%= form_with(model: valor_historico) do |form| %>
  <% if valor_historico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valor_historico.errors.count, "error") %> prohibited this valor_historico from being saved:</h2>

      <ul>
        <% valor_historico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token_criptomoneda %>
    <%= form.text_field :token_criptomoneda %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/valor_historicos/edit.html.erb
<div class="datos">
<h1>Editing Valor Historico</h1>

<%= render 'form', valor_historico: @valor_historico %>

<%= link_to 'Show', @valor_historico %> |
<%= link_to 'Back', valor_historicos_path %>
</div>

app/views/valor_historicos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="tabla">
<h1>Valor Historicos</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Fecha</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valor_historicos.each do |valor_historico| %>
      <tr>
        <td><%= valor_historico.token_criptomoneda %></td>
        <td><%= valor_historico.fecha %></td>
        <td><%= valor_historico.valor %></td>
         <td><%= link_to 'Show', valor_historico %></td>
        <td><%= link_to 'Destroy', valor_historico, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valor Historico', new_valor_historico_path %>
</div>

app/views/valor_historicos/new.html.erb
<h1>New Valor Historico</h1>

<%= render 'form', valor_historico: @valor_historico %>

<%= link_to 'Back', valor_historicos_path %>

app/views/valor_historicos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="datos">
<p>
  <strong>Token criptomoneda:</strong>
  <%= @valor_historico.token_criptomoneda %>
</p>


<p>
  <strong>Fecha:</strong>
  <%= @valor_historico.fecha %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @valor_historico.valor %>
</p>

<%= link_to 'Edit', edit_valor_historico_path(@valor_historico) %> |
<%= link_to 'Back', valor_historicos_path %>
</div>