config/routes.rb
Rails.application.routes.draw do
  resources :balance_divisas
  resources :balance_criptomonedas
  resources :valor_historicos
  resources :criptomonedas
  resources :divisas
  resources :usuarios

  root to:"criptomonedas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format:'json'} do
  	namespace :v1 do
  		resources :balance_divisas
      resources :balance_criptomonedas
      resources :valor_historicos
      resources :criptomonedas
      resources :divisas
      resources :usuarios
  	end
  end
end

app/models/balance_criptomoneda.rb
class BalanceCriptomoneda < ApplicationRecord
	validates :token_criptomoneda, presence: true
	validates :usuario_id, presence: true
	validates_numericality_of :valor, :greater_than_or_equal_to => 0
end

app/controllers/api/v1/balance_criptomonedas_controller.rb
module Api
module V1

class BalanceCriptomonedasController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_balance_criptomoneda, only: [:show, :update, :destroy]

  # GET /balance_criptomonedas
  def index
    @usuarios = Usuario.all
    @balance_criptomonedas = BalanceCriptomoneda.select("balance_criptomonedas.*, criptomonedas.nombre").joins(\
    "INNER JOIN criptomonedas ON criptomonedas.token_criptomoneda = balance_criptomonedas.token_criptomoneda").all.order('valor DESC')

    render json: @balance_criptomonedas
  end

  # GET /balance_criptomonedas/1
  def show
    render json: @balance_criptomoneda
  end

  # POST /balance_criptomonedas
  def create
    @balance_criptomoneda = BalanceCriptomoneda.new(balance_criptomoneda_params)

    if @balance_criptomoneda.save
      render json: @balance_criptomoneda, status: :created, location: @balance_criptomoneda
    else
      render json: @balance_criptomoneda.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /balance_criptomonedas/1
  def update
    if @balance_criptomoneda.update(balance_criptomoneda_params)
      render json: @balance_criptomoneda
    else
      render json: @balance_criptomoneda.errors, status: :unprocessable_entity
    end
  end

  # DELETE /balance_criptomonedas/1
  def destroy
    @balance_criptomoneda.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance_criptomoneda
      @balance_criptomoneda = BalanceCriptomoneda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balance_criptomoneda_params
      params.require(:balance_criptomoneda).permit(:valor, :usuario_id, :token_criptomoneda)
    end
end
end
end

app/controllers/balance_criptomonedas_controller.rb
class BalanceCriptomonedasController < ApplicationController
  before_action :set_balance_criptomoneda, only: %i[ show edit update destroy ]

  # GET /balance_criptomonedas or /balance_criptomonedas.json
  def index
    @balance_criptomonedas = BalanceCriptomoneda.all
  end

  # GET /balance_criptomonedas/1 or /balance_criptomonedas/1.json
  def show
  end

  # GET /balance_criptomonedas/new
  def new
    @balance_criptomoneda = BalanceCriptomoneda.new
  end

  # GET /balance_criptomonedas/1/edit
  def edit
  end

  # POST /balance_criptomonedas or /balance_criptomonedas.json
  def create
    @balance_criptomoneda = BalanceCriptomoneda.new(balance_criptomoneda_params)

    respond_to do |format|
      if @balance_criptomoneda.save
        format.html { redirect_to @balance_criptomoneda, notice: "Balance criptomoneda was successfully created." }
        format.json { render :show, status: :created, location: @balance_criptomoneda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @balance_criptomoneda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balance_criptomonedas/1 or /balance_criptomonedas/1.json
  def update
    respond_to do |format|
      if @balance_criptomoneda.update(balance_criptomoneda_params)
        format.html { redirect_to @balance_criptomoneda, notice: "Balance criptomoneda was successfully updated." }
        format.json { render :show, status: :ok, location: @balance_criptomoneda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @balance_criptomoneda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balance_criptomonedas/1 or /balance_criptomonedas/1.json
  def destroy
    @balance_criptomoneda.destroy
    respond_to do |format|
      format.html { redirect_to balance_criptomonedas_url, notice: "Balance criptomoneda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance_criptomoneda
      @balance_criptomoneda = BalanceCriptomoneda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balance_criptomoneda_params
      params.require(:balance_criptomoneda).permit(:valor, :usuario_id, :token_criptomoneda)
    end
end

app/helpers/balance_criptomonedas_helper.rb
module BalanceCriptomonedasHelper
end

app/views/balance_criptomonedas/_form.html.erb
<%= form_with(model: balance_criptomoneda) do |form| %>
  <% if balance_criptomoneda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(balance_criptomoneda.errors.count, "error") %> prohibited this balance_criptomoneda from being saved:</h2>

      <ul>
        <% balance_criptomoneda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= form.label :token_criptomoneda %>
    <%= form.text_field :token_criptomoneda %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/balance_criptomonedas/edit.html.erb
<div class="datos">
<h1>Editing Balance Criptomoneda</h1>

<%= render 'form', balance_criptomoneda: @balance_criptomoneda %>

<%= link_to 'Show', @balance_criptomoneda %> |
<%= link_to 'Back', balance_criptomonedas_path %>
</div>

app/views/balance_criptomonedas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="tabla">
<h1>Balance Criptomonedas</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Usuario</th>
      <th>Criptomoneda</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @balance_criptomonedas.each do |balance_criptomoneda| %>
      <tr>
        <td><%= balance_criptomoneda.valor %></td>
        <td><%= balance_criptomoneda.usuario_id %></td>
        <td><%= balance_criptomoneda.token_criptomoneda%></td>
        <td><%= link_to 'Show', balance_criptomoneda %></td>
        <td><%= link_to 'Edit', edit_balance_criptomoneda_path(balance_criptomoneda) %></td>
        <td><%= link_to 'Destroy', balance_criptomoneda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Balance Criptomoneda', new_balance_criptomoneda_path %>
</div>

app/views/balance_criptomonedas/new.html.erb
<h1>New Balance Criptomoneda</h1>

<%= render 'form', balance_criptomoneda: @balance_criptomoneda %>

<%= link_to 'Back', balance_criptomonedas_path %>

app/views/balance_criptomonedas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="datos">
<p>
  <strong>Valor:</strong>
  <%= @balance_criptomoneda.valor %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @balance_criptomoneda.usuario_id %>
</p>

<p>
  <strong>Criptomoneda:</strong>
  <%= @balance_criptomoneda.token_criptomoneda %>
</p>

<%= link_to 'Edit', edit_balance_criptomoneda_path(@balance_criptomoneda) %> |
<%= link_to 'Back', balance_criptomonedas_path %>
</div>