config/routes.rb
Rails.application.routes.draw do
  resources :balance_divisas
  resources :balance_criptomonedas
  resources :valor_historicos
  resources :criptomonedas
  resources :divisas
  resources :usuarios

  root to:"criptomonedas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format:'json'} do
  	namespace :v1 do
  		resources :balance_divisas
      resources :balance_criptomonedas
      resources :valor_historicos
      resources :criptomonedas
      resources :divisas
      resources :usuarios
  	end
  end
end

app/models/balance_divisa.rb
class BalanceDivisa < ApplicationRecord
	validates :token_divisa, presence: true
	validates :usuario_id, presence: true
	validates_numericality_of :valor, :greater_than_or_equal_to => 0

end

app/controllers/api/v1/balance_divisas_controller.rb
module Api
module V1

class BalanceDivisasController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_balance_divisa, only: [:show, :update, :destroy]

  # GET /balance_divisas
  def index
    @balance_divisas = BalanceDivisa.select("balance_divisas.*, divisas.nombre_divisa, divisas.simbolo").joins(\
    "INNER JOIN divisas ON divisas.token_divisa = balance_divisas.token_divisa").all.order('valor DESC')

    render json: @balance_divisas
  end

  # GET /balance_divisas/1
  def show
    render json: @balance_divisa
  end

  # POST /balance_divisas
  def create
    @balance_divisa = BalanceDivisa.new(balance_divisa_params)

    if @balance_divisa.save
      render json: @balance_divisa, status: :created, location: @balance_divisa
    else
      render json: @balance_divisa.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /balance_divisas/1
  def update
    if @balance_divisa.update(balance_divisa_params)
      render json: @balance_divisa
    else
      render json: @balance_divisa.errors, status: :unprocessable_entity
    end
  end

  # DELETE /balance_divisas/1
  def destroy
    @balance_divisa.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance_divisa
      @balance_divisa = BalanceDivisa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balance_divisa_params
      params.require(:balance_divisa).permit(:valor, :usuario_id, :token_divisa)
    end
end
end
end

app/controllers/balance_divisas_controller.rb
class BalanceDivisasController < ApplicationController
  before_action :set_balance_divisa, only: %i[ show edit update destroy ]

  # GET /balance_divisas or /balance_divisas.json
  def index
    @balance_divisas = BalanceDivisa.all
  end

  # GET /balance_divisas/1 or /balance_divisas/1.json
  def show
  end

  # GET /balance_divisas/new
  def new
    @balance_divisa = BalanceDivisa.new
  end

  # GET /balance_divisas/1/edit
  def edit
  end

  # POST /balance_divisas or /balance_divisas.json
  def create
    @balance_divisa = BalanceDivisa.new(balance_divisa_params)

    respond_to do |format|
      if @balance_divisa.save
        format.html { redirect_to @balance_divisa, notice: "Balance divisa was successfully created." }
        format.json { render :show, status: :created, location: @balance_divisa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @balance_divisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balance_divisas/1 or /balance_divisas/1.json
  def update
    respond_to do |format|
      if @balance_divisa.update(balance_divisa_params)
        format.html { redirect_to @balance_divisa, notice: "Balance divisa was successfully updated." }
        format.json { render :show, status: :ok, location: @balance_divisa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @balance_divisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balance_divisas/1 or /balance_divisas/1.json
  def destroy
    @balance_divisa.destroy
    respond_to do |format|
      format.html { redirect_to balance_divisas_url, notice: "Balance divisa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance_divisa
      @balance_divisa = BalanceDivisa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balance_divisa_params
      params.require(:balance_divisa).permit(:valor, :usuario_id, :token_divisa)
    end
end

app/helpers/balance_divisas_helper.rb
module BalanceDivisasHelper
end

app/views/balance_divisas/_form.html.erb
<%= form_with(model: balance_divisa) do |form| %>
  <% if balance_divisa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(balance_divisa.errors.count, "error") %> prohibited this balance_divisa from being saved:</h2>

      <ul>
        <% balance_divisa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>

    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>

    <%= form.label :token_divisa %>
    <%= form.text_field :token_divisa %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/balance_divisas/edit.html.erb
<div class="datos">
<h1>Editing Balance Divisa</h1>

<%= render 'form', balance_divisa: @balance_divisa %>

<%= link_to 'Show', @balance_divisa %> |
<%= link_to 'Back', balance_divisas_path %>
</div>

app/views/balance_divisas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="tabla">
<h1>Balance Divisas</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Usuario</th>
      <th>Divisa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @balance_divisas.each do |balance_divisa| %>
      <tr>
        <td><%= balance_divisa.valor %></td>
        <td><%= balance_divisa.usuario_id %></td>
        <td><%= balance_divisa.token_divisa %></td>
        <td><%= link_to 'Show', balance_divisa %></td>
        <td><%= link_to 'Edit', edit_balance_divisa_path(balance_divisa) %></td>
        <td><%= link_to 'Destroy', balance_divisa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Balance Divisa', new_balance_divisa_path %>
</div>

app/views/balance_divisas/new.html.erb
<h1>New Balance Divisa</h1>

<%= render 'form', balance_divisa: @balance_divisa %>

<%= link_to 'Back', balance_divisas_path %>

app/views/balance_divisas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="datos">
<p>
   <strong>Usuario:</strong>
  <%= @balance_divisa.usuario_id %>
</p>


<p>
   <strong>Divisa:</strong>
  <%= @balance_divisa.token_divisa %>
 </p>
 
<p>
   <strong>Valor:</strong>
  <%= @balance_divisa.valor %>
</p>

<%= link_to 'Edit', edit_balance_divisa_path(@balance_divisa) %> |
<%= link_to 'Back', balance_divisas_path %>
</div>