config/routes.rb
Rails.application.routes.draw do
  resources :balance_divisas
  resources :balance_criptomonedas
  resources :valor_historicos
  resources :criptomonedas
  resources :divisas
  resources :usuarios

  root to:"criptomonedas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format:'json'} do
  	namespace :v1 do
  		resources :balance_divisas
      resources :balance_criptomonedas
      resources :valor_historicos
      resources :criptomonedas
      resources :divisas
      resources :usuarios
  	end
  end
end

app/models/divisa.rb
class Divisa < ApplicationRecord
	validates :token_divisa, presence: true
	validates :nombre_divisa, presence: true
	validates :simbolo, presence: true
    validates_uniqueness_of :token_divisa
	validates_uniqueness_of :nombre_divisa
	validates_uniqueness_of :simbolo
	validates_numericality_of :valor, :greater_than => 0
end

app/controllers/api/v1/divisas_controller.rb
module Api
module V1

class DivisasController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_divisa, only: [:show, :update, :destroy]

  # GET /divisas
  def index
    @divisas = Divisa.all.order('valor')

    render json: @divisas
  end

  # GET /divisas/1
  def show
    render json: @divisa
  end

  # POST /divisas
  def create
    @divisa = Divisa.new(divisa_params)

    if @divisa.save
      render json: @divisa, status: :created, location: @divisa
    else
      render json: @divisa.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /divisas/1
  def update
    if @divisa.update(divisa_params)
      render json: @divisa
    else
      render json: @divisa.errors, status: :unprocessable_entity
    end
  end

  # DELETE /divisas/1
  def destroy
    @divisa.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_divisa
      @divisa = Divisa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def divisa_params
      params.require(:divisa).permit(:token_divisa, :nombre_divisa, :valor, :simbolo)
    end
end
end
end

app/controllers/divisas_controller.rb
class DivisasController < ApplicationController
  before_action :set_divisa, only: %i[ show edit update destroy ]

  # GET /divisas or /divisas.json
  def index
    @divisas = Divisa.all
  end

  # GET /divisas/1 or /divisas/1.json
  def show
  end

  # GET /divisas/new
  def new
    @divisa = Divisa.new
  end

  # GET /divisas/1/edit
  def edit
  end

  # POST /divisas or /divisas.json
  def create
    @divisa = Divisa.new(divisa_params)

    respond_to do |format|
      if @divisa.save
        format.html { redirect_to @divisa, notice: "Divisa was successfully created." }
        format.json { render :show, status: :created, location: @divisa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @divisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisas/1 or /divisas/1.json
  def update
    respond_to do |format|
      if @divisa.update(divisa_params)
        format.html { redirect_to @divisa, notice: "Divisa was successfully updated." }
        format.json { render :show, status: :ok, location: @divisa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @divisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisas/1 or /divisas/1.json
  def destroy
    @divisa.destroy
    respond_to do |format|
      format.html { redirect_to divisas_url, notice: "Divisa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_divisa
      @divisa = Divisa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def divisa_params
      params.require(:divisa).permit(:token_divisa, :nombre_divisa, :valor, :simbolo)
    end
end

app/helpers/divisas_helper.rb
module DivisasHelper
end

app/views/divisas/_form.html.erb
<%= form_with(model: divisa) do |form| %>
  <% if divisa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(divisa.errors.count, "error") %> prohibited this divisa from being saved:</h2>

      <ul>
        <% divisa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token_divisa %>
    <%= form.text_field :token_divisa %>
  </div>

  <div class="field">
    <%= form.label :nombre_divisa %>
    <%= form.text_field :nombre_divisa %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :simbolo %>
    <%= form.text_field :simbolo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisas/edit.html.erb
<div class="datos">
<h1>Editing Divisa</h1>

<%= render 'form', divisa: @divisa %>

<%= link_to 'Show', @divisa %> |
<%= link_to 'Back', divisas_path %>
</div>

app/views/divisas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="tabla">
<h1>Divisas</h1>

<table>
  <thead>
    <tr>
      <th>Token divisa</th>
      <th>Nombre divisa</th>
      <th>Valor</th>
      <th>Simbolo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisas.each do |divisa| %>
      <tr>
        <td><%= divisa.token_divisa %></td>
        <td><%= divisa.nombre_divisa %></td>
        <td><%= divisa.valor %></td>
        <td><%= divisa.simbolo %></td>
        <td><%= link_to 'Show', divisa %></td>
        <td><%= link_to 'Edit', edit_divisa_path(divisa) %></td>
        <td><%= link_to 'Destroy', divisa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Divisa', new_divisa_path %>
</div>

app/views/divisas/new.html.erb
<h1>New Divisa</h1>

<%= render 'form', divisa: @divisa %>

<%= link_to 'Back', divisas_path %>

app/views/divisas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="datos">
<p>
  <strong>Token divisa:</strong>
  <%= @divisa.token_divisa %>
</p>

<p>
  <strong>Nombre divisa:</strong>
  <%= @divisa.nombre_divisa %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @divisa.valor %>
</p>

<p>
  <strong>Simbolo:</strong>
  <%= @divisa.simbolo %>
</p>

<%= link_to 'Edit', edit_divisa_path(@divisa) %> |
<%= link_to 'Back', divisas_path %>
</div>